// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-WP_rlNiRNn3UnmRs4xpAkXCk-SbA3wQ',
    appId: '1:385164886188:web:35975ebd47a1f46746df09',
    messagingSenderId: '385164886188',
    projectId: 'jalamico-petpals-1aa60',
    authDomain: 'jalamico-petpals-1aa60.firebaseapp.com',
    storageBucket: 'jalamico-petpals-1aa60.firebasestorage.app',
    measurementId: 'G-R1MMTTMDGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfDLZaWtIyGCYKv8sLpYjgFSqLacBhM0k',
    appId: '1:385164886188:android:5b3fd7c5819f4c5e46df09',
    messagingSenderId: '385164886188',
    projectId: 'jalamico-petpals-1aa60',
    storageBucket: 'jalamico-petpals-1aa60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvONalEcT2UijdYjRPC_EBSTAmLmEBeuo',
    appId: '1:385164886188:ios:ca0d7c2cd01a680046df09',
    messagingSenderId: '385164886188',
    projectId: 'jalamico-petpals-1aa60',
    storageBucket: 'jalamico-petpals-1aa60.firebasestorage.app',
    iosBundleId: 'jalamicoapp.com.petpals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvONalEcT2UijdYjRPC_EBSTAmLmEBeuo',
    appId: '1:385164886188:ios:ca0d7c2cd01a680046df09',
    messagingSenderId: '385164886188',
    projectId: 'jalamico-petpals-1aa60',
    storageBucket: 'jalamico-petpals-1aa60.firebasestorage.app',
    iosBundleId: 'jalamicoapp.com.petpals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-WP_rlNiRNn3UnmRs4xpAkXCk-SbA3wQ',
    appId: '1:385164886188:web:7c57903ecfc81d9d46df09',
    messagingSenderId: '385164886188',
    projectId: 'jalamico-petpals-1aa60',
    authDomain: 'jalamico-petpals-1aa60.firebaseapp.com',
    storageBucket: 'jalamico-petpals-1aa60.firebasestorage.app',
    measurementId: 'G-YX7BL9D6JB',
  );
}
